import LocalizedStrings from 'react-localization';

export let strings = new LocalizedStrings({
   en:{
   	noExist: "The advert doesn't exist anymore",
   	noTitle: "Title not available",
   	with: "with ",
   	noContact: "No contact info available",
   	linkAdvert: "See advert",
   	str1: "The visit ",
   	str2: "is",
   	str3: "was",
   	str4: " on ",
   	str5: " at ",
   	str6: " and created on ",
   	str7: " at ",
   	str8: "with ",
   	str9: "one",
   	str10: "visitors",
   	str11: "visitor",
   	str12: " and a special request stating: ",
   	str13: " and no special request",
   	titleStatus: "Status History",
   	text1: "On ",
   	text2: " at ",
   	text3: " to ",
   	text4: " stating ",
   	pictureName: "Advert Cover",
   	pictureName2: "Deleted advert"
   },
   fr:{
   	noExist: "L'annonce n'existe plus",
   	noTitle: "Titre non disponible",
   	with: "avec ",
   	noContact: "Pas d'info de contact disponible",
   	linkAdvert: "Voir annonces",
   	str1: "La visite ",
   	str2: "est ",
   	str3: "était ",
   	str4: " pour ",
   	str5: " à ",
   	str6: " et créé pour ",
   	str7: " à ",
   	str8: "avec ",
   	str9: "une ",
   	str10: "visteurs",
   	str11: "visiteur",
   	str12: " et ainsi qu'une requête spéciale qui dit: ",
   	str13: " et pas de requête spéciale",
   	titleStatus: "L'historique de status",
   	text1: "Pour ",
   	text2: " à ",
   	text3: " pour ",
   	text4: " qui dit ",
   	pictureName: "Couverture de l'annonce",
   	pictureName2: "Annonce supprimé"
   }
});