import LocalizedStrings from 'react-localization';

export let strings = new LocalizedStrings({
   en:{
   	noExist: "The advert doesn't exist anymore",
   	noTitle: "Title not available",
   	with: "with ",
   	noContact: "No contact info available",
   	linkAdvert: "See advert",
   	str1: "The visit ",
   	str2: "is",
   	str3: "was",
   	str4: " on ",
   	str5: " at ",
   	str6: " and created on ",
   	str7: " at ",
   	str8: "with ",
   	str9: "one",
   	str10: "visitors",
   	str11: "visitor",
   	str12: " and a special request stating: ",
   	str13: " and no special request",
   	titleStatus: "Status History",
   	text1: "On ",
   	text2: " at ",
   	text3: " to ",
   	text4: " stating ",
   	pictureName: "Advert Cover",
   	pictureName2: "Deleted advert"
   },
   fr:{
   	noExist: "aa",
   	noTitle: "aa",
   	with: "aa",
   	noContact: "aa",
   	linkAdvert: "aa",
   	str1: "aa",
   	str2: "aa",
   	str3: "aa",
   	str4: "aa",
   	str5: "aa",
   	str6: "aa",
   	str7: "aa",
   	str8: "aa",
   	str9: "aa",
   	str10: "aa",
   	str11: "aa",
   	str12: "aa",
   	str13: "aa",
   	titleStatus: "aa",
   	text1: "aa",
   	text2: "aa",
   	text3: "aa",
   	text4: "aa",
   	pictureName: "aa",
   	pictureName2: "aa"
   }
});